DROP TABLE IF EXISTS "user" CASCADE;

CREATE TABLE IF NOT EXISTS "user" (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_on TIMESTAMP DEFAULT NOW(),  
  updated_on TIMESTAMP DEFAULT NOW(),
  confirmed_on TIMESTAMP,
  confirmed BOOLEAN DEFAULT FALSE
);
